spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
        - id: UserService
          predicates:
          - Path=/api/users/**,/api/userVisibilityType/**
          uri: http://localhost:8083/


        - id: NotificationService
          predicates:
            - Path=/api/notificationtypes/**,/api/notifications/**
          uri: http://localhost:8081/


        - id: CollectionService
          uri: http://localhost:8082/
          predicates:
            - Path=/api/collections/**,/api/collectionTypes/**


        - id: PostService
          predicates:
            - Path=/api/post/**
          uri: http://localhost:8080/


server:
  port: 8084

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
