package com.example.userservice.controllers;

import com.example.userservice.models.User;
import com.example.userservice.models.UserVisibilityType;
import com.example.userservice.services.UserService;
import com.example.userservice.repositories.UserRepository;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api") // This means URL's start with /demo (after Application path)
public class UserController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserService userService;


    @PostMapping(path = "/users") // Map ONLY POST Requests
    public @ResponseBody ResponseEntity AddNotification (@Valid @RequestBody User requestBody) {
        User user = userService.Create(requestBody);
        return ResponseEntity.status(201).body(user);

    }
    @GetMapping(path = "/users")
    public @ResponseBody ResponseEntity<Iterable<User>> getAllUsers() {
        // This returns a JSON or XML with the users
        Iterable<User> notificationList = userService.List();
        return ResponseEntity.status(200).body(notificationList);
    }

    @GetMapping(path="/users/{id}")
    public @ResponseBody ResponseEntity GetDetails( @PathVariable("id") Integer id) {
        User user = userService.Details(id);
        return ResponseEntity.status(200).body(user);
    }
    @GetMapping(path = "/users/{id}")
    //////////////////////////////
    public @ResponseBody ResponseEntity Delete(@PathVariable("id") Integer id) {
        userService.Delete(id);
        return ResponseEntity.status(204).build();

    }

    @PutMapping("/users/{id}")
    public @ResponseBody ResponseEntity Update(@PathVariable("id") Integer id, @Valid @RequestBody User requestBody) {
        User updated = userService.Update(id, requestBody);
        return ResponseEntity.status(200).body(updated);

    }

    @GetMapping(path="/userVisibilityType")
    public @ResponseBody ResponseEntity GetAllNotificationTypes() {
        Iterable<UserVisibilityType> userVisibilityTypes = userService.ListUserVisibilityTypes();
        return ResponseEntity.status(200).body(userVisibilityTypes);

    }
}