package com.example.collectionservice.services;

import com.example.collectionservice.dto.*;
import com.example.collectionservice.exception.PinwayError;
import com.example.collectionservice.infrastructure.PostService;
import com.example.collectionservice.models.Collection;
import com.example.collectionservice.models.CollectionPost;
import com.example.collectionservice.repositories.CollectionPostRepository;
import com.example.collectionservice.repositories.CollectionRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.*;

@Service
public class CollectionPostServiceImpl implements CollectionPostService {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CollectionPostRepository collectionPostRepository;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CollectionRepository collectionRepository;

    @Autowired
    private PostService postService;

    @Override
    public Collection AddPost(Integer id, CollectionPostCreateDTO collectionPostCreateDTO) {
        Optional<Collection> optCollection = collectionRepository.findById(id);
        if (!optCollection.isPresent())
            throw new PinwayError("Not found Collection with id = " + id);
        // prvjera da li ima post sa IDem ovim datim

        Collection collection = optCollection.get();
        Boolean doesExist = postService.DoesExist(collectionPostCreateDTO.getPostId());
        if (doesExist == false)
            throw new PinwayError("Not found Post with id = " + collectionPostCreateDTO.getPostId());

        CollectionPost collectionPost = new CollectionPost(collectionPostCreateDTO.getPostId(), collection);

        collectionPostRepository.save(collectionPost);
        collectionRepository.increaseNumOfPosts(collection.getId());
        return  collection;
    }

    @Override
    public CollectionResponseDTO GetAllPostsForCollection(Integer id) {
        Optional<Collection> optCollection = collectionRepository.findById(id);
        if (!optCollection.isPresent())
            throw new PinwayError("Not found Collection with id = " + id);

        Collection collection = optCollection.get();
        Set<Long> ids = new HashSet<>();
        for (CollectionPost collectionPost : collection.getCollectionPosts()) {
            Boolean doesExist = postService.DoesExist(collectionPost.getPostId());
            if (!doesExist)
                throw new PinwayError("Not found Post with id = " + collectionPost.getPostId());
            ids.add(collectionPost.getPostId());
        }

        List<PostDTO> postDTOS = postService.GetAllPostsForCollection(ids);
        CollectionVisibilityTypeDTO collectionVisibilityTypeDTO = new CollectionVisibilityTypeDTO(collection.getCollectionVisibilityType().getId(), collection.getCollectionVisibilityType().getType());
        CollectionDTO collectionDTO = new CollectionDTO(collection.getId(), collection.getName(), collectionVisibilityTypeDTO);

        CollectionResponseDTO collectionResponseDTO = new CollectionResponseDTO(collectionDTO, postDTOS);

        return collectionResponseDTO;
    }
}
